apiVersion: v1
kind: Pod
metadata:
  name: net-test
  labels:
    role: net-test
spec:
  containers:
  - name: nettest
    image: jonlangemak/net_tools

---
apiVersion: v1
kind: Service
metadata:
  name: net-test-service  
  labels:
    service: net-test
spec:
  selector:
    role: net-test
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
