apiVersion: v1
kind: Service
metadata:
  name: net-test3-service  
  labels:
    service: net-test3
spec:
  selector:
    role: net-test3
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80

